//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraniteWorld.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GraniteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraniteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraniteWorld.App_LocalResources.GraniteResource", typeof(GraniteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a product to load.
        /// </summary>
        public static string ChooseProductLoadPrefix {
            get {
                return ResourceManager.GetString("ChooseProductLoadPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Load.
        /// </summary>
        public static string CompleteLoadButton {
            get {
                return ResourceManager.GetString("CompleteLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Portal.
        /// </summary>
        public static string CustomerPortalTab {
            get {
                return ResourceManager.GetString("CustomerPortalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Received.
        /// </summary>
        public static string DateTimeReceivedPrefix {
            get {
                return ResourceManager.GetString("DateTimeReceivedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Portal.
        /// </summary>
        public static string EmployeePortalTab {
            get {
                return ResourceManager.GetString("EmployeePortalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter inventory details.
        /// </summary>
        public static string EnterInventoryDetailsHeader {
            get {
                return ResourceManager.GetString("EnterInventoryDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granite World.
        /// </summary>
        public static string GraniteWorldHeader {
            get {
                return ResourceManager.GetString("GraniteWorldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthPrefix {
            get {
                return ResourceManager.GetString("LengthPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Inventory.
        /// </summary>
        public static string ReceiveInventoryHeader {
            get {
                return ResourceManager.GetString("ReceiveInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WeightPrefix {
            get {
                return ResourceManager.GetString("WeightPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (default).
        /// </summary>
        public static string WidthPrefix {
            get {
                return ResourceManager.GetString("WidthPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Purchase History.
        /// </summary>
        public static string YourPurchaseHistoryHeader {
            get {
                return ResourceManager.GetString("YourPurchaseHistoryHeader", resourceCulture);
            }
        }
    }
}
